spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: redis  # 세션을 Redis로 저장
    redis:
      flush-mode: immediate  # (옵션) 즉시 플러시 모드로 설정하여 세션이 변경될 때마다 즉시 Redis에 반영
      namespace: myapp-session  # (옵션) 세션 데이터를 위한 네임스페이스

  redis:
    host: localhost
    port: 6379
    password: your-redis-password  # (옵션) Redis 서버에 비밀번호가 설정되어 있다면 추가
    lettuce:
      pool:
        max-active: 8  # 최대 활성 연결 수
        max-idle: 8    # 최대 유휴 연결 수
        min-idle: 0    # 최소 유휴 연결 수

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8083
