server:
  port: 8081
feign-data:
  url : "http://localhost:8084"

weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "kASQEznlUpHNFnsXoucR1xFy1Rej3ldegAFRXhHNsQgp1nCtnlRZKJLe+cquSnV/3fe8DvkQXGVsHt8RFtsWmA=="