spring:
  datasource:

    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
<<<<<<< HEAD

weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "kASQEznlUpHNFnsXoucR1xFy1Rej3ldegAFRXhHNsQgp1nCtnlRZKJLe+cquSnV/3fe8DvkQXGVsHt8RFtsWmA=="
=======
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
>>>>>>> 2ab4e023df6867cd976f8545a4bb64c0cb52043d

server:
  port: 8085