
spring:
  session:
    store-type: redis
    redis:
      namespace: my-app-session

  data:
      redis:
        host: localhost
        #      password: 1234
        port: 6379
        timeout: 60000ms

  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: lo  # 원하는 사용자 이름으로 변경
      password: 1234  # 원하는 비밀번호로 변경



mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8088